name: Rust CI Pipeline

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/*.yml'
    branches:
      - '!main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Test
      run: cargo test --verbose
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
  doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo doc --verbose
