on:
  workflow_dispatch:

name: Crates.io publish

jobs:
  crates-io-release:
    runs-on: ubuntu-latest
    steps:
      - name: Login
        run: |-
          echo "${{ secrets.CARGO_REGISTRY_TOKEN }}" | cargo login
      - name: Publish
        run: cargo publish

