on:
  release:
    types: [published]

name: Crates.io publish

jobs:
  crates-io-release:
    runs-on: ubuntu-latest
    steps:
      - name: Login 
        run: cargo login
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Publish
        run: cargo publish
