name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      rust--tag_name: ${{ steps.release.outputs.hello-rust--tag_name}}
      rust--release_created: ${{ steps.release.outputs.hello-rust--release_created}}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: release-please-manifest.json
      - name: Print release outputs for debugging
        continue-on-error: true
        run: |
          echo "Release outputs:"
          echo "${{ toJson(steps.release.outputs) }}"

  release:
    if: ${{needs.release-please.outputs.rust--release_created}}
    runs-on: ubuntu-latest
    needs: release-please
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Test
        run: cargo test
      - name: Build
        run: cargo build --verbose --release --target x86_64-unknown-linux-gnu
      - name: Upload Release Artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ needs.release-please.outputs.rust--tag_name }} target/x86_64-unknown-linux-gnu/release/hello_rust
